### ISSUE TITLE
2.2.0rc1 released

### ISSUE THREAD

**Issue by pixelr0** [kyrofa/darktable-snap#2]
https://github.com/darktable-org/darktable/releases/tag/release-2.2.0rc1

**Comment by pixelr0** [comment]
teh snap is getting owld X-)

**Comment by kyrofa** [comment]
Thanks for the heads up @pixelr0. The stable channel is tracking stable releases (though I missed v2.0.7, whoops-- fixed now). In response to your request, I've started tracking the release candidates in the candidate channel, so you can install v2.2.0rc1 with:

    $ sudo snap install --candidate darktable-kyrofa

Note that, yes, Launchpad can grab code from GitHub (in fact, that's how it builds this snap), but in order to automatically build it upstream Darktable would need to include the `snapcraft.yaml` provided here. They don't, so we provide it here, which means we need to update the URL to the tarball whenever they update it, which spins up a new build in Launchpad.

**Comment by pixelr0** [comment]
oh, i see :D thanks!  pretty awesome tech them snaps
