### ISSUE TITLE
Execute tool scripts (like purge_non_existing_images.sh)

### ISSUE THREAD

**Issue by frigi83** [kyrofa/darktable-snap#33]
Maybe this issue is related with #13 

It is possible to launch the scripts in the `tools/` [directory](https://github.com/darktable-org/darktable/tree/master/tools) of DT? There are some helpful scripts to clean the library from non existing images (like [purge_non_existing_images.sh](https://github.com/darktable-org/darktable/blob/master/tools/purge_non_existing_images.sh)).

**Comment by kyrofa** [comment]
It's not beautiful, but you can always do something like this:

```
$ snap run --shell darktable <<'EOF'
$SNAP/usr/share/darktable/tools/purge_non_existing_images.sh <args>
EOF
```

However, that particular script doesn't run because the snap is missing the sqlite3 binary. Just looking at that script, it doesn't appear to use darktable in any way, so if you had sqlite3 installed on your machine you could just run it directly:

    $ /snap/darktable/current/usr/share/darktable/tools/purge_non_existing_images.sh <args>

**Comment by frigi83** [comment]
Thank's for the reply.

I think the only way is to copy the script locally and change the location of the `library.db` file in:

```
DBFILE=$HOME/snap/darktable/current/library.db
```

I hope that DT developer will integrate these functions into the GUI as soon as possible.

Greetings from Switzerland
